# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The UWIN/eScience Working Group in Neuroinformatics
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Neuroinformatics is an emerging field of research that comprises the use of
  modern data-intensive technologies in neuroscience. Its practice requires
  both broad knowledge of neuroscience as well as substantive competency in
  data science. The WING is a working group at the University of Washington
  (UW) eScience Institute and the University of Washington Institute for
  Neuroengineering (UWIN) that focuses on neuroinformatics methods and their
  role in understanding the brain.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uwescience.github.io/neuroinformatics" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
